Add project
GreetyCr/review_your_project pull request #1
Opened 2023-05-01 20:23 UTC by GreetyCr

Project added for review

2023-05-01 20:45 UTC, GreetyCr commented
Hi @GreetyCr,

![Alt Text](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

### Don't Worry 🙏

It's ok that the project is not perfect as you first project is done all by yourself, but there are some aspects that we can improve before hoping into the next project

### Highlights

- ✔️ Nice overall layout.
- ✔️ Great design 
- ✔️ Correct GitHub flow

### Required Changes ♻️

- Make sure all the linterns are passing in the proper way shown in #1 
- Make sure the boxes are aligned with flexbox:
<img width="1279" alt="Screenshot 2023-05-01 at 2 38 50 PM" src="https://user-images.githubusercontent.com/89504485/235527004-e32e58c5-fa7f-46b6-beda-a20a2af7c31f.png">

### Optional suggestions ✅

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

### Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> Note: Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.

### Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My GitHub: @GreetyCr 
- This is My Slack: Randall Bonilla
- This is My gmail: greetysoftwarejs@gmail.com

2023-05-01 20:54 UTC, GreetyCr commented on style.css
> +  display: flex;
You use a lot of display flex in a different amount of classes, you can fix this by creating a class and add that class in all the HTML elements to use DRY (Don't Repeat Yourself)

2023-05-01 20:54 UTC, GreetyCr commented on style.css
> +  color: #aaaaaa;
Remember to use best practices! You can change "#aaaaaa" for "#aaa"

2023-05-01 20:54 UTC, GreetyCr commented on style.css
> +}
It is important to get used to best practices, remember leaving a line at the end of the style.css files

2023-05-01 20:54 UTC, GreetyCr commented on style.css
> +
In the class .links and .likes you use the exact same styles, you can save some lines of code using DRY merging this classes:
.likes,
.links {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

2023-05-01 20:54 UTC, GreetyCr commented on index.html
> +                src="./assets/vibe with Aquinas.webp"
Make sure that if you are showing images, check the extension of the element or file you are using to prevent gifs, videos or sounds showing instead of images

2023-05-01 22:15 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @GreetyCr 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Perform code review
- ✔️ Use GitHub inline comment feature

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-01 22:15 UTC, abdulhamiid commented on index.html
> +                src="./assets/vibe with Aquinas.webp"
- [ ] Your suggestion sounds like an order, please kindly rephrase it into suggestions 🤓. e.g saying "I think it would be better to use semantic tags" sounds nicer than "Use semantic tags," doesn't it?

2023-05-01 22:15 UTC, abdulhamiid commented on style.css
> +}
Instead of giving orders, make suggestions 🤓🛠

2023-05-01 22:15 UTC, abdulhamiid commented on style.css
> +  color: #aaaaaa;
> Remember to use best practices! You can change "#aaaaaa" for "#aaa"

- [ ] Your suggestion sounds like an order, Instead of giving orders, please kindly make suggestions 🤓. e.g saying "I think it would be better to use semantic tags" sounds nicer than "Use semantic tags," doesn't it?

- [ ] Also please remember to explain why you request a change - it might be obvious for you but not for someone else. 💪

2023-05-01 22:16 UTC, abdulhamiid commented on style.css
> +  display: flex;
Hello @GreetyCr, You did great Using the GitHub inline comment and also giving a review. 👍 💯 , But I think there are still some improvements you need to make before moving to the next milestone.

According to the lesson [How to give a code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md)

- [ ] Please let's remember to be polite and clear in our comments - our job here is to help another person improve in a friendly way. 🤗

- [ ] Instead of giving orders, let's make suggestions 🤓🛠. e.g saying "I think it would be better to use  . . . " sounds nicer than "Use . . . " doesn't it?

You can consider using these two words for polite comment 
`Please do this` or `Kindly do this`

2023-05-03 15:36 UTC, GreetyCr commented on style.css
> +  display: flex;
I noticed that you've used `display: flex` in several classes throughout your code. To adhere to the DRY (Don't Repeat Yourself) principle, I would kindly suggest creating a dedicated class for it and applying that class to the necessary HTML elements. This approach should help make the code more maintainable and efficient. Keep up the good work!

2023-05-03 15:40 UTC, GreetyCr commented on style.css
> +  color: #aaaaaa;
I noticed you've used the color code `#aaaaaa` in your CSS. As a friendly suggestion, consider following best practices by using the shorthand version `#aaa`. This will help make the code more concise and easier to read. Keep up the great work!

2023-05-03 15:41 UTC, GreetyCr commented on style.css
> +}
I observed that the style.css file doesn't have a blank line at the end. As a friendly suggestion, following best practices by adding a blank line at the end of CSS files can enhance code readability and maintainability. Keep up the fantastic work!

2023-05-03 15:42 UTC, GreetyCr commented on index.html
> +                src="./assets/vibe with Aquinas.webp"
I'd like to kindly suggest that when displaying images, it's a good idea to verify the file extension of the element being used. This can help prevent unexpected content such as GIFs, videos, or sounds from appearing in place of images. Keep up the excellent work!

2023-05-03 21:40 UTC, merged